import Foundation
import CleanerCore
import CleanerPlatform
import CleanerPluginAPI

/// Cleans Xcode DerivedData — build intermediates & indexes Xcode regenerates automatically.
/// 🟢 Safe: no user source, fully rebuildable. One finding per project's DerivedData folder
/// (specs/plugins/plugin-xcode.md, v0.1 subset).
public struct XcodeDerivedDataPlugin: CleanerPlugin {
    public init() {}

    public var metadata: PluginMetadata {
        .init(id: PluginID("dev.cleaner.xcode.deriveddata"), name: "Xcode DerivedData",
              category: .developerCache, defaultRisk: .safe)
    }

    private func root(_ c: PluginContext) -> String {
        c.home + "/Library/Developer/Xcode/DerivedData"
    }

    public func declaredRoots(_ context: PluginContext) -> [String] { [root(context)] }

    public func scan(_ context: PluginContext) async throws -> [Finding] {
        PluginSupport.children(of: root(context), context).compactMap { path in
            // Skip Xcode's own shared indexes bucket name if present; treat each project dir.
            let name = (path as NSString).lastPathComponent
            let stale = isProbablyStale(name)
            let rationale = stale
                ? "project appears to no longer exist; Xcode rebuilds if reopened"
                : "regenerated by Xcode on next build"
            return PluginSupport.finding(
                path: path, context: context, plugin: metadata, category: .developerCache,
                score: 96, recoverability: .manual, disposition: .stage, rationale: rationale)
        }
    }

    /// Heuristic placeholder for v0.1 — real staleness (WorkspacePath in info.plist) is a
    /// follow-up. DerivedData names are "<Project>-<hash>"; we never rely on the name to decide
    /// *safety* (it's Safe regardless), only to phrase the rationale.
    private func isProbablyStale(_ name: String) -> Bool {
        name.contains("-") == false
    }
}
