import Testing
import Foundation
@testable import CleanerReport
import CleanerCore

@Suite("Report: JSON + Markdown")
struct ReportTests {
    private func sample() -> ScanResult {
        let f = Finding(item: Item(id: ItemID("a"), title: "MyApp-abc", path: "/x/MyApp-abc",
                        evidence: Evidence(allocatedSize: 2_048_000)),
                        pluginID: PluginID("dev.cleaner.xcode.deriveddata"),
                        category: .developerCache, safetyScore: SafetyScore(96),
                        recoverability: .manual, rationale: "regenerated by Xcode on next build")
        return ScanResult(findings: [f])
    }

    @Test("markdown report is grouped by source, icon-free, with a risk column")
    func markdown() {
        let md = MarkdownReport.render(sample(), generatedAt: "2026-07-06T00:00:00Z",
                                       names: [PluginID("dev.cleaner.xcode.deriveddata"): "Xcode DerivedData"])
        #expect(md.contains("# cleaner — Storage Report"))
        #expect(md.contains("**Total reclaimable: 2.0 MB**"))
        #expect(md.contains("| Source | Reclaimable | Risk |"))
        #expect(md.contains("| Xcode DerivedData | 2.0 MB | safe |"))
        #expect(!md.contains("🟢") && !md.contains("🛠"))   // no emoji
    }

    @Test("empty scan renders a tidy markdown message")
    func emptyMarkdown() {
        let md = MarkdownReport.render(ScanResult(), generatedAt: "t")
        #expect(md.contains("Nothing reclaimable found"))
    }

    @Test("summary renderer is a plain aligned list, icon-free & bar-free (no-color)")
    func summary() {
        let r = SummaryRenderer(useColor: false, width: 80)
        let out = r.analyze(sample(), elapsed: "1.2s")
        #expect(out.contains("DISK RECLAIMABLE"))    // header
        #expect(out.contains("Developer Cache"))     // category
        #expect(out.contains("2.0 MB"))              // right-aligned size
        #expect(out.contains("Total"))
        #expect(!out.contains("█"))                  // no bars
        #expect(!out.contains("🟢") && !out.contains("🛠"))  // no emoji
    }

    @Test("analyze JSON has schemaVersion and totals")
    func json() throws {
        let dto = ReportJSON.analyze(sample())
        #expect(dto.schemaVersion == ReportJSON.schemaVersion)
        #expect(dto.totalReclaimable.bytes == 2_048_000)
        let text = try ReportJSON.encode(dto)
        #expect(text.contains("\"schemaVersion\""))
        #expect(text.contains("\"command\" : \"analyze\""))
    }
}
