import Testing
import Foundation
@testable import CleanerReport
import CleanerCore

@Suite("Report: JSON + Markdown")
struct ReportTests {
    private func sample() -> ScanResult {
        let f = Finding(item: Item(id: ItemID("a"), title: "MyApp-abc", path: "/x/MyApp-abc",
                        evidence: Evidence(allocatedSize: 2_048_000)),
                        pluginID: PluginID("dev.cleaner.xcode.deriveddata"),
                        category: .developerCache, safetyScore: SafetyScore(96),
                        recoverability: .manual, rationale: "regenerated by Xcode on next build")
        return ScanResult(findings: [f])
    }

    @Test("markdown report contains header, total, table and item")
    func markdown() {
        let md = MarkdownReport.render(sample(), generatedAt: "2026-07-06T00:00:00Z")
        #expect(md.contains("# cleaner — Storage Report"))
        #expect(md.contains("**Total reclaimable: 2.0 MB**"))
        #expect(md.contains("| Category | Reclaimable | Items |"))
        #expect(md.contains("🟢 **2.0 MB** — `MyApp-abc`"))
    }

    @Test("empty scan renders a tidy markdown message")
    func emptyMarkdown() {
        let md = MarkdownReport.render(ScanResult(), generatedAt: "t")
        #expect(md.contains("Nothing reclaimable found"))
    }

    @Test("analyze JSON has schemaVersion and totals")
    func json() throws {
        let dto = ReportJSON.analyze(sample())
        #expect(dto.schemaVersion == ReportJSON.schemaVersion)
        #expect(dto.totalReclaimable.bytes == 2_048_000)
        let text = try ReportJSON.encode(dto)
        #expect(text.contains("\"schemaVersion\""))
        #expect(text.contains("\"command\" : \"analyze\""))
    }
}
