/// An `Item` plus the assessment used to present and act on it (Constitution glossary).
///
/// Invariant: `risk` is consistent with `safetyScore.impliedRisk` *unless* a plugin or the
/// scorer deliberately tightened it (a plugin may only lower confidence, never raise it —
/// DM-2). `recoverability == .none` forces `risk == .dangerous` (Art. 4.3).
public struct Finding: Sendable, Hashable, Codable, Identifiable {
    public let item: Item
    public let pluginID: PluginID
    public let category: Category
    public let safetyScore: SafetyScore
    public let risk: RiskLevel
    public let recoverability: Recoverability
    /// Proposed default disposition (engine may override for safety).
    public let proposedDisposition: Disposition
    /// One-line, human rationale ("regenerated by Xcode on next build").
    public let rationale: String

    public var id: ItemID { item.id }

    public init(
        item: Item,
        pluginID: PluginID,
        category: Category,
        safetyScore: SafetyScore,
        recoverability: Recoverability,
        proposedDisposition: Disposition = .stage,
        rationale: String,
        riskOverride: RiskLevel? = nil
    ) {
        self.item = item
        self.pluginID = pluginID
        self.category = category
        self.safetyScore = safetyScore
        self.recoverability = recoverability
        self.proposedDisposition = proposedDisposition
        self.rationale = rationale

        // Derive risk from score, then apply the two non-negotiable tighten rules.
        // A plugin's override may only *raise* risk (tighten), never lower it (DM-2).
        var derived = safetyScore.impliedRisk
        if recoverability.forcesDangerous { derived = .dangerous }
        if let o = riskOverride, o > derived { derived = o }
        self.risk = derived
    }

    public var reclaimableSize: ByteCount { item.reclaimableSize }
}
